import type { Metadata } from "next";
import { AppSidebar } from "@/components/sidebar/Sidebar";
import {
   SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar"
import Navbar from "@/components/sidebar/Navbar"
export const metadata: Metadata = {
  title: "Nex Link",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<>
   <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <Navbar/>
    {children}
    </SidebarInset>
    </SidebarProvider>
  </>
        
  );
}